== Colophon

=== Suggested citation

Raymond M, Rodrigues A & Russell L A. 
Introduction to GBIF course 
First edition. 
GBIF Secretariat: Copenhagen. 
https://doi.org/10.35035/doc-xxxx-xxxx.

=== Authors

Mélianie Raymond, Andrew Rodrigues and Laura Anne Russell

=== Contributors

GBIF Secretariat staff.

=== Licence

The course _Introduction to GBIF_ is licensed under https://creativecommons.org/licenses/by-sa/4.0[Creative Commons Attribution-ShareAlike 4.0 Unported License].

=== Persistent URI

https://doi.org/10.35035/doc-xxxx-xxxx

=== Document control

First edition, March 2021

// include reference to provenance if possible/relevant
https://doi.org/10.15468/doc-yyyy-yyyy[Second edition], March 2015, by Due Autore and https://orcid.org/0000-0000-0000-0000[Troisième Auteur].

Originally based on an earlier publication, _Towards establishing the special guide to something_.

=== Cover image

// Caption. Credit, source, licence.
 Microporus xanthopus (Fr.) Kuntze observed in Malaysia by siburanlai (licensed under http://creativecommons.org/licenses/by-nc/4.0/[CC BY-NC 4.0]).
