[description]
== Course description

****
This course provides an introduction to GBIF, the data available in GBIF's portal, accessing that data and information about engaging with GBIF and its community of practice.

Topics include:

* Information about GBIF
* GBIF-mediated data
* Data publishing
* Data access
* GBIF community of practice

This course is comprised of video and written instruction and paired with quizzes and practical exercises.
****

=== Audience

This course is designed for individuals who work in biodiversity research or policy institutions and contribute to or use data from the GBIF portal. The instruction provided is particularly useful for those who have a desire to know more about GBIF and its place in the biodiversity community and want to engage further with GBIF.

=== Prerequisites

There are no prerequisites for this course.
This course serves as a prerequisite for other GBIF courses.

Participants should have a good command of English. While efforts are made to provide materials in other languages, instruction videos will be in English with subtitles in other languages.

